variables:
- group: khiva-csharp-VG
- name: codecov_t
  value: $(CODECOV_TOKEN)

jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: self
        clean: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
        displayName: "Use Python 3.7"
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 4.7.2'
        inputs:
          versionSpec: '4.7.2'
      - task: NuGetCommand@2
        displayName: "Nuget restore Khiva.sln"
        inputs:
          command: 'restore'
          solution: 'Khiva.sln'
          verbosityRestore: 'Quiet'
      - script: |
          source .CI/azure-pipelines/install-arrayfire.sh
          source .CI/azure-pipelines/install-khiva.sh
        displayName: "Install ArrayFire and Khiva"
      - script: source .CI/azure-pipelines/build_and_test_mono.sh
        displayName: "Build and test"
      - script: bash <(curl -s https://codecov.io/bash) -t $(codecov_t)
        condition: succeeded()
        displayName: "Codecov"
      - task: PublishTestResults@2
        inputs:
          testRunner: 'NUnit'
          testResultsFiles: '**/TestResult.xml'
          testRunTitle: 'Test results'
          platform: 'x64'
          configuration: 'Debug'
          displayName: "Publish test results"
          condition: succeeded()

  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - checkout: self
        clean: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
        displayName: "Use Python 3.7"
      - script: |
          wget https://download.mono-project.com/archive/5.20.1/macos-10-universal/MonoFramework-MDK-5.20.1.19.macos10.xamarin.universal.pkg -O mono.pkg
          sudo installer -pkg mono.pkg -target /
        displayName: "Install Mono"
      - task: NuGetCommand@2
        displayName: "Nuget restore Khiva.sln"
        inputs:
          command: 'restore'
          solution: 'Khiva.sln'
          verbosityRestore: 'Quiet'
      - script: |
          source .CI/azure-pipelines/install-arrayfire.sh
          source .CI/azure-pipelines/install-khiva.sh
        displayName: "Install ArrayFire and Khiva"
      - script: source .CI/azure-pipelines/build_and_test_mono.sh
        displayName: "Build and test"
      - script: bash <(curl -s https://codecov.io/bash) -t $(codecov_t)
        condition: succeeded()
        displayName: "Codecov"
      - task: PublishTestResults@2
        inputs:
          testRunner: 'NUnit'
          testResultsFiles: '**/TestResult.xml'
          testRunTitle: 'Test results'
          platform: 'x64'
          configuration: 'Debug'
          displayName: "Publish test results"
          condition: succeeded()

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - checkout: self
        clean: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
        displayName: "Use Python 3.7"
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'echo $Env:PATH;'
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 4.7.2'
        inputs:
          versionSpec: '4.7.2'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'if(!(Test-Path -Path "C:/Program Files/ArrayFire" )){wget https://www.dropbox.com/s/13wnbd1qynjmw0i/ArrayFire-v3.6.2.zip?dl=1 -O ArrayFire-v3.6.2.zip }'
        displayName: "Download ArrayFire"
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'if(!(Test-Path -Path "C:/Program Files/ArrayFire" )){ 7z x ArrayFire-v3.6.2.zip -o"C:/Program Files" }'
        displayName: "Extract ArrayFire zip"
      - script: reg add HKCU\Software\Kitware\CMake\Packages\ArrayFire /v ArrayFire_CMake_DIR /d "C:/Program Files/ArrayFire/v3/cmake" /f
        displayName: "Reg add"
      - script: vcpkg install --triplet x64-windows gtest eigen3
        displayName: "Download ArrayFire dependencies"
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'if ($(INSTALL_KHIVA_METHOD) -eq "installer"){
            if(!(Test-Path -Path "C:/Program Files/Khiva" )){ wget https://github.com/shapelets/khiva/releases/download/v0.2.2/khiva-v0.2.2.exe -O khiva-v0.2.2.exe};
            if(!(Test-Path -Path "C:/Program Files/Khiva" )){ ./khiva-v0.2.2.exe /S };
          }else{
            git clone -q https://github.com/shapelets/khiva.git C:/khiva-library ;
            cd C:/khiva-library ;
            mkdir build ;
            cd build ;
            pip install conan ;
            conan remote add conan-mpusz https://api.bintray.com/conan/mpusz/conan-mpusz ;
            conan install .. --build missing ;
            cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/vcpkg/scripts/buildsystems/vcpkg.cmake -G"$env:GENERATOR" ;
            cmake --build . --config Release -- /m ;
          };
          ls "C:\Program Files";'
        env: 
          GENERATOR: "Visual Studio 15 2017 Win64"
        displayName: "Install khiva"
      - script: choco install Codecov
        displayName: "Install codecov"
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          solution: 'Khiva.sln'
          verbosityRestore: 'Quiet'
        displayName: "Nuget restore"
      - task: VSBuild@1
        inputs:
          solution: 'Khiva.sln'
          platform: 'x64'
          configuration: 'Debug'
          maximumCpuCount: true
          msbuildArchitecture: 'x64'
        displayName: "Build solution Khiva.sln"
      - powershell: |
          $Env:PATH += "C:\Program Files\Khiva\v0\lib"
          echo $Env:PATH
          .\packages\OpenCover.4.6.519\tools\OpenCover.Console -register:user -target:".\packages\NUnit.ConsoleRunner.3.9.0\tools\nunit3-console.exe" -targetargs:"test/bin/x64/Debug/Khiva.Tests.dll --inprocess" -output:"coverage.xml" -filter:"+[Khiva*]* -[Khiva.Tests]*"
          codecov -f coverage.xml
        displayName: "Run tests"
      - script: codecov -f coverage.xml -t $(codecov_t)
        condition: succeeded()
        displayName: "Codecov" 
      - task: PublishTestResults@2
        inputs:
          testRunner: 'NUnit'
          testResultsFiles: '**/TestResult.xml'
          testRunTitle: 'Test results'
          platform: 'x64'
          configuration: 'Debug'
          displayName: "Publish test results"