jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - checkout: self
        clean: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 4.7.2'
        inputs:
          versionSpec: 4.7.2
      - task: NuGetCommand@2
        displayName: "Nuget restore Khiva.sln"
        inputs:
          command: 'restore'
          solution: 'Khiva.sln'
          verbosityRestore: 'Quiet'
      - script: |
          source .CI/azure-pipelines/install-arrayfire.sh
        displayName: "Install"
      - script: source .CI/azure-pipelines/build_and_test_mono.sh
        displayName: "Build and test"
      - script: bash <(curl -s https://codecov.io/bash)
        condition: succeeded()
        displayName: "Codecov"

  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
      runtime: 9.1
    steps:
      - checkout: self
        clean: true
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
      - task: NuGetToolInstaller@0
        displayName: 'Use NuGet 4.7.2'
        inputs:
          versionSpec: 4.7.2
      - task: NuGetCommand@2
        displayName: "Nuget restore Khiva.sln"
        inputs:
          command: 'restore'
          solution: 'Khiva.sln'
          verbosityRestore: 'Quiet'
      - script: |
          source .CI/azure-pipelines/install-arrayfire.sh
          source .CI/azure-pipelines/install-khiva.sh
        displayName: "Install"
      - script: source .CI/azure-pipelines/build_and_test_mono.sh
        displayName: "Build and test"
      - script: bash <(curl -s https://codecov.io/bash)
        condition: succeeded()
        displayName: "Codecov"

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: DownloadFile@1
        inputs:
          FileUrl: 'https://www.dropbox.com/s/13wnbd1qynjmw0i/ArrayFire-v3.6.2.zip?dl=1'
        condition: not (Test-Path -Path "C:\Program Files\ArrayFire")
# Use the environment variables input below to pass secret variables to this script.'