variables:
  LD_LIBRARY_PATH: /usr/local/lib:/usr/local/include
  DYLD_FALLBACK_LIBRARY_PATH: /usr/local/include
  BOOST_PATH: Libraries/boost_1_67_0
  AF_PATH: /opt/arrayfire-3
  KHIVA_PATH: ./khiva-library
  LDFLAGS: -L/usr/local/opt/openssl/lib
  CPPFLAGS: -I/usr/local/opt/openssl/include
  PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
  PATH: /usr/local/opt/openssl/bin:/usr/bin/:/bin/:/usr/local/bin:/usr/local/lib:/usr/local/share:/usr/local/include:/usr/lib:$(AF_PATH)/lib:$(KHIVA_PATH)/lib:$(PATH)
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    clean: true
  - task: NuGetToolInstaller@0
    displayName: 'Use NuGet 4.7.2'
    inputs:
      versionSpec: 4.7.2
  - script: echo $PATH
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: echo hello from macOS
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo hello from Windows